version: '3.1'
services:
  statistics:
    build: stats-server
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - server
      - stats-db
    environment:
      - STAT_DB_URL=jdbc:postgresql://postgresql:6542/stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    restart: always
    container_name: postgresql_stats
    ports:
        - "6542:5432"
    depends_on:
    - ewm-db
    - server
    volumes:
    - ./sql/schema_stat.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - STATS_URL=http://server:9090
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: ewm
    container_name: ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_URL=http://statistics:9090
      - SERVER_DB_URL=jdbc:postgresql://postgresql:6541/ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    restart: always
    container_name: postgresql_ewm
    ports:
        - "6541:5432"
    volumes:
        - ./sql/schema_ewm.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
