logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
server:
  port: 8080
spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:file:./db/ewm_server
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.h2dialect
        format_sql: true
statistics:
  url: http://ewm-statistics:9090