logging:
    level:
        org:
            springframework:
                orm:
                    jpa: INFO
                    jpa.JpaTransactionManager: DEBUG
                transaction: INFO
server:
    port: 8080
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        url: ${SERVER_DB_URL}
        username: ${POSTGRES_USER}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
statistics:
    url: ${STATS_URL}