server:
  port: 9090
spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:file:./db/ewm_statistics
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.h2dialect
        format_sql: true
