CREATE TABLE IF NOT EXISTS hits (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 app VARCHAR(255) NOT NULL,
 uri VARCHAR(255) NOT NULL,
 ip VARCHAR(255) NOT NULL,
 timestamp BIGINT NOT NULL,
 CONSTRAINT pk_endpoint_hits PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS view_stats (
  app VARCHAR(255) NOT NULL UNIQUE,
  uri VARCHAR(255),
  hits BIGINT,
  CONSTRAINT pk_view_stats PRIMARY KEY (app)
);

CREATE FUNCTION add_hits()
    RETURNS trigger AS '
    BEGIN
        UPDATE
            view_stats SET hits = hits + 1 WHERE app == tg_argv[0]
            AND uri = tg_argv[1];
        RETURN NEW;
    END;
' LANGUAGE  plpgsql;

-- Создание триггера
CREATE TRIGGER set_view_stats_hits BEFORE INSERT ON hits FOR EACH ROW
EXECUTE PROCEDURE add_hits(app, uri);